const fs=require('node:fs'),path=require('node:path'),{execFile}=require('node:child_process'),{promisify}=require('node:util'),{pathToFileURL}=require('node:url');
const {readDirectory,readEntry}=require('./valve-package');
const {atomicSave}=require('./core');
function mapName(value){const name=String(value||'').split(/[\\/]/).pop();if(!/^[a-zA-Z0-9_-]{1,100}$/.test(name))throw Error('地图名称无效。');return name.toLowerCase();}
function keyValues(text){if(text.length>1024*1024)throw Error('地图说明过大。');const tokens=[];const lexer=/\s+|\/\/[^\r\n]*|"((?:\\.|[^"\\])*)"|([{}])|([^\s{}"]+)/gy;let offset=0;while(offset<text.length){lexer.lastIndex=offset;const token=lexer.exec(text);if(!token)throw Error('地图说明格式无效。');offset=lexer.lastIndex;if(token[1]!==undefined)tokens.push(token[1].replace(/\\"/g,'"'));else if(token[2]||token[3])tokens.push(token[2]||token[3]);if(tokens.length>10000)throw Error('地图说明过长。');}let i=0;function object(depth){if(depth>16)throw Error('地图说明嵌套过深。');const result=Object.create(null);while(i<tokens.length&&tokens[i]!=='}'){const key=tokens[i++],next=tokens[i++];if(key==='{'||next===undefined||next==='}')throw Error('地图说明格式无效。');if(next==='{'){result[key]=object(depth+1);if(tokens[i++]!=='}')throw Error('地图说明缺少闭合。');}else result[key]=next;}return result;}const parsed=object(0);if(i!==tokens.length)throw Error('地图说明格式无效。');return parsed;}
function overview(text,map){const tree=keyValues(text),values=tree[map]||Object.values(tree)[0];if(!values||typeof values!=='object')throw Error('未找到地图坐标定义。');const posX=Number(values.pos_x),posY=Number(values.pos_y),scale=Number(values.scale);if(!Number.isFinite(posX)||!Number.isFinite(posY)||!Number.isFinite(scale)||scale<=0||scale>100)throw Error('地图坐标定义无效。');const sections=Object.entries(values.verticalsections||{}).map(([name,value])=>({name,min:Number(value.AltitudeMin),max:Number(value.AltitudeMax)})).filter(x=>Number.isFinite(x.min)&&Number.isFinite(x.max)&&x.max>x.min);return {map,posX,posY,scale,sections};}
function coordinates({X,Y},map){return {x:(Number(X)-map.posX)/(map.scale*1024),y:(map.posY-Number(Y))/(map.scale*1024)};}
function createMapService({directory,decoder}){const pending=new Map(),children=new Set();let stopping=false;fs.mkdirSync(directory,{recursive:true});
 async function load(gameExe,name){if(stopping)throw Error('地图服务已关闭。');const map=mapName(name),root=path.resolve(path.dirname(gameExe),'../../csgo'),vpk=path.join(root,'pak01_dir.vpk');if(!fs.existsSync(vpk))throw Error('未找到 CS2 地图资源，请在偏好设置中指定 CS2 安装目录。');const key=vpk+':'+map;if(pending.has(key))return pending.get(key);const task=(async()=>{const entries=readDirectory(vpk),metaEntry=entries.find(e=>e.path===`resource/overviews/${map}.txt`),imageEntries=entries.filter(e=>e.path.startsWith(`panorama/images/overheadmaps/${map}`)&&/^panorama\/images\/overheadmaps\/[a-z0-9_-]+_radar_psd\.vtex_c$/.test(e.path));if(!metaEntry||!imageEntries.some(e=>e.path.endsWith(`/${map}_radar_psd.vtex_c`)))throw Error('当前 CS2 没有这张地图的雷达资源，可继续使用坐标网格。');const meta=overview(readEntry(vpk,metaEntry,{maxBytes:1024*1024}).toString('utf8'),map),folder=path.join(directory,map);fs.mkdirSync(folder,{recursive:true});const signature=[metaEntry,...imageEntries].map(e=>e.path+':'+e.crc).join('|');let saved;try{saved=JSON.parse(fs.readFileSync(path.join(folder,'map.json'),'utf8'));}catch{}if(saved?.signature===signature&&saved.layers.every(l=>fs.existsSync(l.path)))return {...saved,layers:saved.layers.map(l=>({...l,url:pathToFileURL(l.path).href}))};if(!fs.existsSync(decoder))throw Error('地图解码工具缺失，请重新安装软件。');const layers=[];for(const entry of imageEntries){const basename=path.basename(entry.path,'.vtex_c'),input=path.join(folder,basename+'.vtex_c'),output=path.join(folder,basename+'.png');fs.writeFileSync(input,readEntry(vpk,entry,{maxBytes:32*1024*1024}));try{const operation=promisify(execFile)(decoder,['-i',input,'-o',output],{windowsHide:true,timeout:60000,maxBuffer:1024*1024});children.add(operation.child);try{await operation;}finally{children.delete(operation.child);}if(!fs.existsSync(output)||!fs.readFileSync(output).subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')))throw Error('地图图像解码失败。');layers.push({name:basename.replace(map+'_','').replace('_psd',''),path:output});}finally{fs.unlinkSync(input);}}const result={...meta,signature,layers};atomicSave(path.join(folder,'map.json'),result);return {...result,layers:layers.map(l=>({...l,url:pathToFileURL(l.path).href}))};})();pending.set(key,task);try{return await task;}finally{pending.delete(key);}}
 async function stop(){stopping=true;for(const child of children)child.kill();await Promise.allSettled([...pending.values()]);}
 return {load,stop,get busy(){return pending.size>0;}};
}
module.exports={mapName,keyValues,overview,coordinates,createMapService};
