const http=require('node:http'),crypto=require('node:crypto');
const {activityAt}=require('./studio-voice');
function createVoiceHud(){let server,url='',voice=null,roster=[],tick=0,loading;
 function state(){const speaking=voice?activityAt(voice,tick).map(p=>({id:p.steamid||String(p.entity),name:roster.find(r=>r.id===p.steamid)?.name||p.steamid||'未识别玩家'})):[];return {tick,speaking,mode:'preview'};}
 async function start(){if(url)return url;if(loading)return loading;loading=(async()=>{const prefix='/voice/'+crypto.randomBytes(18).toString('hex'),nonce=crypto.randomBytes(16).toString('hex');server=http.createServer((req,res)=>{const host=req.headers.host||'';if(host!==`127.0.0.1:${server.address().port}`||req.method!=='GET'){res.writeHead(403);res.end();return;}res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');if(req.url===prefix+'/state'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state()));return;}if(req.url!==prefix){res.writeHead(404);res.end();return;}res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Security-Policy',`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'`);res.end(`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><style>body{margin:0;background:transparent;color:#fff;font:22px "Microsoft YaHei",sans-serif}#hud{display:grid;gap:8px;padding:16px}.speaker{display:flex;gap:12px;align-items:center;background:rgba(17,23,30,.88);border-left:4px solid #ff8d3c;border-radius:7px;padding:12px 18px;width:420px}.dot{color:#ff8d3c}</style><div id="hud"></div><script nonce="${nonce}">async function update(){try{const r=await fetch(location.pathname+'/state'),s=await r.json(),root=document.querySelector('#hud');root.replaceChildren(...s.speaking.map(p=>{const row=document.createElement('div');row.className='speaker';const icon=document.createElement('span');icon.className='dot';icon.textContent='◉';const name=document.createElement('span');name.textContent=p.name;row.append(icon,name);return row;}));}catch{}setTimeout(update,150)}update();</script></html>`);});await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});url=`http://127.0.0.1:${server.address().port}${prefix}`;return url;})();try{return await loading;}finally{loading=null;}}
 function prepare(value,players){voice=value;roster=players;tick=0;}
 function seek(value){const number=Number(value);if(!Number.isFinite(number)||number<0||number>(voice?.maxTick||0)+64)throw Error('语音预览 Tick 无效。');tick=Math.floor(number);return state();}
 function clear(){voice=null;tick=0;}
 async function close(){clear();await loading?.catch(()=>{});if(server)await new Promise(resolve=>server.close(resolve));url='';server=null;}
 return {start,prepare,seek,state,clear,close,status:()=>({url,mode:'preview',tick})};
}
module.exports={createVoiceHud};
