const StudioPage=(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let call,tab='review',snapshot={library:{items:[]},recording:{clips:[]},editor:{projects:[]},settings:{},secrets:{}},selected=null,meta=null,analysis=null,chosen=new Set(),busy=false,message='从下载库点“复盘”，或添加本地 DEM。',ai=null,scenes=[],frames=[],frame=0,playing=null,poll=null;
  let project={name:'我的精彩集锦',segments:[]},preview='';
  let radarMap=null,mapError='',mapLayer=0,mapImages=[],voice=null,voiceTick=0,voicePlaying=null,hudUrl='';
  const tabs=[['review','玩家复盘'],['radar','地图回放'],['voice','语音活动'],['record','POV 录制'],['edit','视频剪辑'],['settings','连接与画面']];
  const button=(action,label,extra='')=>`<button type="button" class="button small" data-studio="${action}" ${extra}>${label}</button>`;
  function html(){return '<div id="studioRoot"></div>';}
  function paint(){const root=document.querySelector('#studioRoot');if(!root)return;
    root.innerHTML=`<div class="studio-tabs">${tabs.map(([id,label])=>`<button class="button ${tab===id?'primary':'subtle'}" data-studio-tab="${id}">${label}</button>`).join('')}</div><div class="studio-status" role="status">${esc(message)}${busy?' 请稍候…':''}</div>${content()}`;
    if(tab==='radar')drawRadar();
    if(tab==='voice')drawVoice();
    root.querySelectorAll('button,input,select').forEach(el=>{if(busy&&!el.hasAttribute('data-studio-tab'))el.disabled=true;});
  }
  function content(){
    if(tab==='settings')return settingsHTML();
    if(tab==='edit')return editorHTML();
    if(tab==='record')return recordHTML();
    if(tab==='radar')return radarHTML();
    if(tab==='voice')return voiceHTML();
    const records=snapshot.library.items;
    return `<div class="studio-columns"><section class="studio-card"><div class="studio-card-title"><h2>复盘库 <small>${records.length} 场</small></h2><div>${button('open','添加 DEM')}${button('scan','扫描目录')}</div></div><div class="studio-library">${records.map(row=>`<div class="studio-file ${selected?.id===row.id?'selected':''}"><div><strong>${esc(row.filename)}</strong><small>${esc(row.meta?.map||'未解析')} · ${esc(({ready:'可复盘',parsing:'解析中',error:'解析失败'})[row.status]||row.status)}</small></div>${button('select','复盘',`data-id="${esc(row.id)}"`)}</div>`).join('')||'<p class="studio-empty">尚无录像。已下载的 DEM 可直接送到这里。</p>'}</div></section><section class="studio-card"><div class="studio-card-title"><h2>${esc(selected?.filename||'选择一场录像')}</h2>${selected?button('play','Steam 播放'):''}</div>${meta?`<p class="studio-meta">${esc(meta.map)} · ${meta.totalRounds} 回合 · ${esc(meta.server)}</p><div class="studio-player-grid">${meta.players.map(player=>`<button class="studio-player ${analysis?.player.id===player.id?'selected':''}" data-studio="analyze" data-player="${esc(player.id)}"><strong>${esc(player.name)}</strong><span>${player.kills} / ${player.deaths} / ${player.assists}</span><small>ADR ${player.adr} · HS ${player.hs}%</small></button>`).join('')}</div>`:'<p class="studio-empty">读取玩家名单后，选择要复盘的人。</p>'}${analysis?analysisHTML():''}</section></div>`;
  }
  function analysisHTML(){const p=analysis.player;return `<div class="studio-summary"><span><b>${p.kills}</b>击杀</span><span><b>${p.deaths}</b>死亡</span><span><b>${p.kd}</b>K/D</span><span><b>${p.adr}</b>ADR</span></div><div class="studio-card-title"><h3>${esc(p.name)} 的关键片段</h3><div>${button('best','选精彩回合')}${button('to-record','去录制')}</div></div><div class="studio-clip-list">${analysis.clips.map(clip=>`<div class="studio-clip"><input type="checkbox" data-studio-clip="${esc(clip.id)}" aria-label="选择 ${esc(clip.label)}" ${chosen.has(clip.id)?'checked':''}><div><strong>${esc(clip.label)}</strong><small>第 ${clip.round} 回合 · Tick ${clip.startTick}–${clip.endTick}</small></div>${button('radar-clip','坐标',`data-clip="${esc(clip.id)}"`)}</div>`).join('')}</div>`;}
  function radarHTML(){return `<section class="studio-card"><div class="studio-card-title"><div><h2>比赛地图回放</h2><p class="studio-meta">底图读取本机 CS2 资源，按游戏地图坐标显示真实玩家位置。</p></div>${button('radar-load','读取当前回合')}</div>${analysis?`<div class="studio-inline"><label>起始 Tick <input id="radarStart" type="number" min="0" value="${frames[0]?.tick||analysis.clips[0]?.startTick||0}"></label>${button('radar-load','读取 30 秒')}${button('radar-play',playing?'暂停':'播放')}${radarMap?`<label>地图层<select id="mapLayer">${radarMap.layers.map((l,i)=>`<option value="${i}" ${i===mapLayer?'selected':''}>${esc(l.name)}</option>`).join('')}</select></label>`:''}</div><canvas id="studioRadar" width="760" height="540"></canvas><input id="radarFrame" type="range" min="0" max="${Math.max(0,frames.length-1)}" value="${frame}" aria-label="回放时间"><p id="radarCaption" class="studio-meta"></p><p class="studio-meta">${radarMap?'已载入 '+esc(radarMap.map)+' 地图':esc(mapError||'载入坐标后自动读取地图；没有资源时显示坐标网格。')} · 纹理解码：Source 2 Viewer</p>`:'<p class="studio-empty">先在“玩家复盘”选择并分析一名玩家。</p>'}</section>`;}
  function voiceHTML(){return `<section class="studio-card"><div class="studio-card-title"><div><h2>语音活动与 HUD 预览</h2><p class="studio-meta">读取录像中的真实语音包，显示说话玩家与时间，不播放音频或转写对话。</p></div>${selected?button('voice-load','分析语音'):''}</div>${voice?`<p class="studio-meta">${voice.packetCount.toLocaleString()} 个语音包 · ${voice.players.length} 个身份 · ${voice.tickRate} Tick/s</p>${voice.packetCount?`<div class="studio-inline">${button('voice-play',voicePlaying?'暂停预览':'播放预览')}${button('voice-url','复制 OBS HUD 地址')}${button('voice-obs','添加到 OBS 场景')}</div><input id="voiceRange" type="range" min="0" max="${voice.maxTick}" value="${Math.floor(voiceTick)}" aria-label="语音时间"><p id="voiceCaption" class="studio-meta"></p><div id="voiceActive" class="studio-voice-active"></div><div class="studio-voice-timeline">${voice.players.map(p=>`<div class="studio-voice-row"><strong>${esc(meta.players.find(r=>r.id===p.steamid)?.name||p.steamid||'未识别玩家')}</strong><div>${p.segments.map(s=>`<button type="button" class="studio-voice-segment" data-studio="voice-segment" data-tick="${s.startTick}" style="left:${s.startTick/voice.maxTick*100}%;width:${Math.max(.15,(s.endTick-s.startTick)/voice.maxTick*100)}%" title="Tick ${s.startTick}–${s.endTick}" aria-label="跳到语音 Tick ${s.startTick}"></button>`).join('')}</div></div>`).join('')}</div><p class="studio-meta">OBS HUD 跟随本页预览时间；尚未与游戏内正在播放的录像实时同步。录制开始时关闭预览提示。</p>${hudUrl?`<p class="studio-meta">HUD 地址已复制：${esc(hudUrl)}</p>`:''}`:'<p class="studio-empty">该录像没有保存可用语音包。</p>'}`:'<p class="studio-empty">选择录像后点击“分析语音”。</p>'}</section>`;}
  function drawVoice(){const caption=document.querySelector('#voiceCaption'),root=document.querySelector('#voiceActive');if(!voice||!root)return;const active=voice.players.filter(p=>p.segments.some(s=>s.startTick<=voiceTick&&s.endTick>=voiceTick));root.innerHTML=active.map(p=>`<span class="studio-speaker">◉ ${esc(meta.players.find(r=>r.id===p.steamid)?.name||p.steamid||'未识别玩家')}</span>`).join('')||'<span class="studio-meta">当前没有语音包活动</span>';if(caption)caption.textContent=`Tick ${Math.floor(voiceTick)} · ${Math.floor(voiceTick/voice.tickRate/60)}:${String(Math.floor(voiceTick/voice.tickRate)%60).padStart(2,'0')}`;const slider=document.querySelector('#voiceRange');if(slider)slider.value=Math.floor(voiceTick);}
  async function seekVoice(tick){voiceTick=Math.max(0,Math.min(voice?.maxTick||0,Number(tick)||0));drawVoice();await call('studio-voice-seek',{tick:voiceTick});}
  function recordHTML(){const status=snapshot.recording.task;return `<div class="studio-columns"><section class="studio-card"><h2>自动录制个人 POV</h2><p class="studio-meta">通过 Steam 启动录像，自动切换玩家；游戏确认视角后由 OBS 录制。控制台需保留默认 ~ 键。录制时不要手动暂停或切换视角。</p><div class="studio-inline">${button('obs','检查 OBS')}<select id="obsScene" aria-label="录制场景"><option value="">使用 OBS 当前场景</option>${scenes.map(s=>`<option value="${esc(s)}" ${snapshot.settings.obsScene===s?'selected':''}>${esc(s)}</option>`).join('')}</select></div>${analysis?`<p>当前：${esc(analysis.player.name)} · 已选 ${chosen.size} 个片段</p><label class="studio-check"><input id="recordWhole" type="checkbox"> 录制整场该玩家镜头</label><div class="studio-inline">${button('record','开始录制')}${button('record-cancel','停止录制')}${button('ai','AI 点评与选片')}${button('auto-project','按选片建剪辑')}</div>`:'<p class="studio-empty">请先选择玩家并分析，再选中要录制的片段。</p>'}${status?`<div class="studio-status" id="recordStatus">${esc(status.message)} · ${status.done}/${status.total}</div>`:''}${ai?`<div class="studio-ai"><h3>AI 点评</h3><p>${esc(ai.commentary)}</p></div>`:''}</section><section class="studio-card"><h2>录制素材</h2>${snapshot.recording.clips.map(clip=>`<div class="studio-file"><div><strong>${esc(clip.name)}</strong><small>${esc(clip.player)} · ${clip.complete?'已完成':'部分录制'}</small></div>${button('edit-recording','加入剪辑',`data-id="${esc(clip.id)}"`)}</div>`).join('')||'<p class="studio-empty">录制完成的视频会自动出现在这里。</p>'}</section></div>`;}
  function editorHTML(){return `<section class="studio-card"><div class="studio-card-title"><h2>我的剪辑</h2><div>${button('video-import','添加视频')}${button('project-new','新项目')}</div></div><div class="studio-inline"><input id="projectName" aria-label="项目名称" value="${esc(project.name)}"><select id="projectSelect" aria-label="已保存项目"><option value="">打开已保存项目</option>${snapshot.editor.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('')}</select>${button('project-save','保存项目')}${button('project-export','导出 MP4')}${button('export-cancel','取消导出')}</div>${preview?`<video class="studio-video" controls src="${esc(preview)}"></video>`:''}<div class="studio-edit-list">${project.segments.map((s,i)=>`<div class="studio-edit-row" data-segment="${i}"><strong title="${esc(s.path)}">${esc(s.path.split(/[\\/]/).pop())}</strong><label>起点 <input type="number" min="0" step="0.1" data-field="start" value="${s.start}"></label><label>终点 <input type="number" min="0" step="0.1" data-field="end" value="${s.end}"></label><label>速度 <select data-field="speed">${[0.5,1,1.5,2].map(v=>`<option value="${v}" ${v===s.speed?'selected':''}>${v}×</option>`).join('')}</select></label><label>音量 <input type="number" min="0" max="2" step="0.1" data-field="volume" value="${s.volume}"></label><label>标题<input data-field="title" value="${esc(s.title||'')}"></label><label>色调<select data-field="look">${[['original','原色'],['cinema','电影'],['mono','黑白']].map(([v,l])=>`<option value="${v}" ${s.look===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="studio-check"><input type="checkbox" data-field="fade" ${s.fade?'checked':''}> 淡入淡出</label><div>${button('segment-preview','预览',`data-index="${i}"`)}${button('segment-up','↑',`data-index="${i}"`)}${button('segment-down','↓',`data-index="${i}"`)}${button('segment-remove','移除',`data-index="${i}"`)}</div></div>`).join('')||'<p class="studio-empty">添加录制素材或本地视频，设置起止秒数、速度和音量，然后导出。输出统一为 1080p / 60fps MP4，原始素材保留。</p>'}</div><p id="exportStatus" class="studio-meta">${esc(snapshot.editor.job?.message||'')}</p></section>`;}
  function settingsHTML(){const s=snapshot.settings;return `<form class="studio-card" id="studioSettings"><h2>连接设置</h2><p class="studio-meta">在 OBS 的“工具 → WebSocket 服务器设置”启用服务。密码和 AI 密钥由 Windows 本机加密保存。空白密钥保留原值。</p><div class="studio-settings-grid"><label>OBS 地址<input name="obsAddress" value="${esc(s.obsAddress||'ws://127.0.0.1:4455')}"></label><label>OBS 密码<input name="obsPassword" type="password" autocomplete="new-password" placeholder="${snapshot.secrets.obsPasswordSaved?'已加密保存':'可留空'}"></label><label>AI 接口基础地址<input name="aiBase" value="${esc(s.aiBase||'')}" placeholder="https://服务地址/v1"></label><label>AI 模型<input name="aiModel" value="${esc(s.aiModel||'')}"></label><label>AI 密钥<input name="aiKey" type="password" autocomplete="new-password" placeholder="${snapshot.secrets.aiKeySaved?'已加密保存':'本机 AI 服务可留空'}"></label></div><p class="studio-meta">点击“AI 点评与选片”才会将所选玩家的事件摘要发送给你配置的 AI 服务，不上传整个 DEM。</p><h3>回放画面</h3><div class="studio-inline"><label class="studio-check"><input name="xray" type="checkbox" ${s.xray!==false?'checked':''}> 显示透视</label><label class="studio-check"><input name="cleanHud" type="checkbox" ${s.cleanHud?'checked':''}> 简洁 HUD</label></div><div class="studio-inline"><button class="button primary" type="submit">保存设置</button>${button('secrets-clear','清除连接密钥')}</div></form>`;}
  async function refresh(){snapshot=await call('studio-state');}
  function resetPreview(){clearInterval(voicePlaying);voicePlaying=null;voice=null;voiceTick=0;hudUrl='';radarMap=null;mapImages=[];frames=[];frame=0;call('studio-voice-clear').catch(()=>{});}
  async function run(label,fn){if(busy)return;busy=true;message=label;paint();try{await fn();message='已完成。';}catch(e){message=e.message||String(e);}finally{busy=false;paint();}}
  async function select(id){await run('正在读取玩家与回合',async()=>{resetPreview();selected=snapshot.library.items.find(x=>x.id===id);meta=await call('review-players',{id});analysis=null;ai=null;chosen.clear();await refresh();});}
  async function openRecord(id,index=0){await run('正在从下载库加入复盘',async()=>{const reply=await call('review-open-record',{id,index});resetPreview();selected=reply.record;meta=reply.meta;analysis=null;ai=null;chosen.clear();await refresh();});}
  function best(){chosen=new Set(analysis?.clips.filter(x=>x.kind==='highlight').sort((a,b)=>b.score-a.score).slice(0,10).map(x=>x.id)||[]);}
  async function radarLoad(start){await run('正在读取地图与真实玩家坐标',async()=>{const value=await call('review-radar',{id:selected.id,tick:start,endTick:Number(start)+1920});const grouped=new Map();for(const p of value.positions){if(!grouped.has(p.tick))grouped.set(p.tick,[]);grouped.get(p.tick).push(p);}frames=[...grouped].sort((a,b)=>a[0]-b[0]).map(([tick,positions])=>({tick,positions}));frame=0;try{radarMap=await call('review-map',{id:selected.id});mapLayer=0;mapImages=await Promise.all(radarMap.layers.map(l=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('地图图片读取失败。'));img.src=l.url;})));mapError='';}catch(e){radarMap=null;mapImages=[];mapError=e.message;}});}
  function drawRadar(){const canvas=document.querySelector('#studioRadar');if(!canvas)return;const ctx=canvas.getContext('2d');ctx.fillStyle='#10161d';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#293844';for(let x=0;x<canvas.width;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke();}for(let y=0;y<canvas.height;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke();}
    const size=Math.min(canvas.width,canvas.height),left=(canvas.width-size)/2,top=(canvas.height-size)/2;if(radarMap&&mapImages[mapLayer])ctx.drawImage(mapImages[mapLayer],left,top,size,size);
    const valid=frames.flatMap(f=>f.positions).filter(p=>Number.isFinite(p.X)&&Number.isFinite(p.Y));if(!valid.length)return;const minX=Math.min(...valid.map(p=>p.X))-200,maxX=Math.max(...valid.map(p=>p.X))+200,minY=Math.min(...valid.map(p=>p.Y))-200,maxY=Math.max(...valid.map(p=>p.Y))+200;const scale=Math.min((canvas.width-60)/(maxX-minX),(canvas.height-60)/(maxY-minY));
    for(const p of frames[frame]?.positions||[]){if(!Number.isFinite(p.X)||!Number.isFinite(p.Y))continue;const x=radarMap?left+(p.X-radarMap.posX)/(radarMap.scale*1024)*size:30+(p.X-minX)*scale,y=radarMap?top+(radarMap.posY-p.Y)/(radarMap.scale*1024)*size:canvas.height-30-(p.Y-minY)*scale;ctx.globalAlpha=p.health>0?1:0.35;ctx.fillStyle=String(p.steamid)===analysis?.player.id?'#ff8d3c':p.team_num===2?'#e5b95c':'#65b9ec';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();if(Number.isFinite(p.yaw)){ctx.strokeStyle=ctx.fillStyle;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(p.yaw*Math.PI/180)*15,y-Math.sin(p.yaw*Math.PI/180)*15);ctx.stroke();}ctx.font='11px sans-serif';ctx.fillText(String(p.name||'').trim().slice(0,12),x+9,y+3);ctx.globalAlpha=1;}
    const caption=document.querySelector('#radarCaption');if(caption)caption.textContent=`Tick ${frames[frame]?.tick||0} · 橙色：所选玩家 · 蓝色：CT · 黄色：T · 暗色：死亡`;
  }
  function captureProject(){const name=document.querySelector('#projectName');if(name)project.name=name.value;document.querySelectorAll('[data-segment]').forEach(row=>{const s=project.segments[Number(row.dataset.segment)];row.querySelectorAll('[data-field]').forEach(input=>{const field=input.dataset.field;s[field]=field==='fade'?input.checked:['title','look'].includes(field)?input.value:Number(input.value);});});}
  async function clicks(e){const target=e.target.closest('[data-studio]');if(!target)return;const action=target.dataset.studio,index=Number(target.dataset.index);
    if(action==='voice-load')return run('正在解析录像中的真实语音包',async()=>{clearInterval(voicePlaying);voicePlaying=null;voice=await call('review-voice',{id:selected.id});voiceTick=voice.players[0]?.segments[0]?.startTick||0;await seekVoice(voiceTick);});
    if(action==='voice-segment')return seekVoice(target.dataset.tick);
    if(action==='voice-url')return run('正在准备语音 HUD',async()=>{hudUrl=(await call('studio-voice-hud')).url;});
    if(action==='voice-obs')return run('正在添加 OBS 浏览器来源',async()=>{await call('studio-voice-obs');});
    if(action==='voice-play'){if(voicePlaying){clearInterval(voicePlaying);voicePlaying=null;}else if(voice){voicePlaying=setInterval(async()=>{if(!document.querySelector('#voiceRange')||voiceTick>=voice.maxTick){clearInterval(voicePlaying);voicePlaying=null;return;}try{await seekVoice(voiceTick+voice.tickRate/10);}catch(error){clearInterval(voicePlaying);voicePlaying=null;message=error.message;paint();}},100);}paint();return;}
    if(action==='select')return select(target.dataset.id);
    if(action==='scan')return run('正在扫描录像目录',async()=>{await call('review-scan');await refresh();});
    if(action==='open')return run('正在添加 DEM',async()=>{const reply=await call('review-open-file');if(reply){selected=reply.record;meta=reply.meta;analysis=null;await refresh();}});
    if(action==='analyze')return run('正在分析玩家',async()=>{analysis=await call('review-analyze',{id:selected.id,playerId:target.dataset.player});best();});
    if(action==='play')return run('正在通过 Steam 载入录像',()=>call('review-play',{id:selected.id}));
    if(action==='best'){best();paint();return;}
    if(action==='to-record'){tab='record';paint();return;}
    if(action==='radar-clip'){const clip=analysis.clips.find(c=>c.id===target.dataset.clip);tab='radar';paint();return radarLoad(clip.startTick);}
    if(action==='radar-load')return analysis?radarLoad(document.querySelector('#radarStart')?.value||0):undefined;
    if(action==='radar-play'){if(playing){clearInterval(playing);playing=null;}else if(frames.length)playing=setInterval(()=>{if(!document.querySelector('#studioRadar')){clearInterval(playing);playing=null;return;}frame=(frame+1)%frames.length;document.querySelector('#radarFrame').value=frame;drawRadar();},500);return;}
    if(action==='obs')return run('正在连接 OBS',async()=>{const status=await call('studio-obs-status');scenes=status.scenes;message=`OBS ${status.version} 已连接`;});
    if(action==='record'){const whole=document.querySelector('#recordWhole')?.checked,scene=document.querySelector('#obsScene')?.value;return run('正在准备录制',async()=>{await call('studio-settings',{...snapshot.settings,obsScene:scene});await call('studio-record',{id:selected.id,playerId:analysis.player.id,clipIds:[...chosen],whole});await refresh();});}
    if(action==='record-cancel'){await call('studio-record-cancel');await refresh();paint();return;}
    if(action==='ai')return run('正在请求 AI 点评',async()=>{ai=await call('studio-ai',{id:selected.id,playerId:analysis.player.id});if(ai.clipIds.length)chosen=new Set(ai.clipIds);});
    if(action==='auto-project')return run('正在按选片顺序生成剪辑',async()=>{project=await call('studio-auto-project',{id:selected.id,playerId:analysis.player.id,clipIds:[...chosen]});await refresh();tab='edit';});
    if(action==='video-import')return run('正在添加素材',async()=>{const videos=await call('studio-video-import');for(const video of videos)project.segments.push({path:video.path,start:0,end:Math.round(Math.min(video.duration,30)*10)/10,speed:1,volume:1,preview:video.preview,noAudio:video.noAudio});});
    if(action==='edit-recording')return run('正在加入录制素材',async()=>{const video=await call('studio-video-recorded',{id:target.dataset.id});project.segments.push({path:video.path,start:0,end:video.duration,speed:1,volume:1,preview:video.preview,noAudio:video.noAudio});tab='edit';});
    if(action==='project-new'){project={name:'我的精彩集锦',segments:[]};preview='';paint();return;}
    if(action.startsWith('segment-')){captureProject();if(action==='segment-remove')project.segments.splice(index,1);if(action==='segment-up'&&index>0)[project.segments[index-1],project.segments[index]]=[project.segments[index],project.segments[index-1]];if(action==='segment-down'&&index<project.segments.length-1)[project.segments[index+1],project.segments[index]]=[project.segments[index],project.segments[index+1]];if(action==='segment-preview')preview=project.segments[index].preview||'file:///'+encodeURI(project.segments[index].path.replace(/\\/g,'/'));paint();return;}
    if(action==='project-save'||action==='project-export'){captureProject();return run(action==='project-save'?'正在保存剪辑':'正在准备导出',async()=>{project=await call('studio-project-save',project);await refresh();if(action==='project-export')await call('studio-project-export',{id:project.id});});}
    if(action==='export-cancel'){await call('studio-export-cancel');return;}
    if(action==='secrets-clear')return run('正在清除连接密钥',async()=>{await call('studio-settings',{...snapshot.settings,clearSecrets:true});await refresh();});
  }
  function mount(api,{refresh=true}={}){call=api;paint();if(refresh)run('正在读取工作室',async()=>{await StudioPage.refresh();});const root=document.querySelector('#studioRoot');root.addEventListener('click',e=>{const nav=e.target.closest('[data-studio-tab]');if(nav){if(tab==='edit')captureProject();if(tab==='voice'){clearInterval(voicePlaying);voicePlaying=null;}tab=nav.dataset.studioTab;paint();}else clicks(e).catch(error=>{message=error.message;paint();});});root.addEventListener('input',e=>{if(e.target.id==='voiceRange')seekVoice(e.target.value).catch(error=>{message=error.message;paint();});});root.addEventListener('change',e=>{if(e.target.dataset.studioClip){e.target.checked?chosen.add(e.target.dataset.studioClip):chosen.delete(e.target.dataset.studioClip);}if(e.target.id==='radarFrame'){frame=Number(e.target.value);drawRadar();}if(e.target.id==='mapLayer'){mapLayer=Number(e.target.value);drawRadar();}if(e.target.id==='projectSelect'){const p=snapshot.editor.projects.find(x=>x.id===e.target.value);if(p){project=structuredClone(p);preview='';paint();}}});root.addEventListener('submit',e=>{if(e.target.id!=='studioSettings')return;e.preventDefault();const form=e.target,data=Object.fromEntries(new FormData(form));data.xray=form.elements.xray.checked;data.cleanHud=form.elements.cleanHud.checked;run('正在保存连接',async()=>{await call('studio-settings',data);await StudioPage.refresh();});});clearInterval(poll);poll=setInterval(async()=>{if(!document.querySelector('#studioRoot')){clearInterval(poll);return;}try{const previous=snapshot.recording.task?.phase,clips=snapshot.recording.clips.length;await StudioPage.refresh();if(tab==='record'&&(previous!==snapshot.recording.task?.phase||clips!==snapshot.recording.clips.length))paint();const r=document.querySelector('#recordStatus');if(r&&snapshot.recording.task)r.textContent=snapshot.recording.task.message;const x=document.querySelector('#exportStatus');if(x&&snapshot.editor.job)x.textContent=`${snapshot.editor.job.message} · ${snapshot.editor.job.done}/${snapshot.editor.job.total}`;}catch{}},2000);}
  return {html,mount,openRecord,refresh,paint};
})();
